//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CVs()
        {
            this.DinhDang_rtbx_UV = new HashSet<DinhDang_rtbx_UV>();
        }
    
        public string Id { get; set; }
        public string Avatar { get; set; }
        public string JobPos { get; set; }
        public string CareerGoal { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public string Activity { get; set; }
        public string Award { get; set; }
        public string Certificate { get; set; }
        public string UploadDate { get; set; }
    
        public virtual UNGVIEN UNGVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhDang_rtbx_UV> DinhDang_rtbx_UV { get; set; }
    }
}
