//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeTai_02_Entities : DbContext
    {
        public DeTai_02_Entities()
            : base("name=DeTai_02_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<CVs> CVs { get; set; }
        public virtual DbSet<DinhDang_rtbx_NTD> DinhDang_rtbx_NTD { get; set; }
        public virtual DbSet<DinhDang_rtbx_UV> DinhDang_rtbx_UV { get; set; }
        public virtual DbSet<JobPostings> JobPostings { get; set; }
        public virtual DbSet<Letter> Letter { get; set; }
        public virtual DbSet<LichPhongVan> LichPhongVan { get; set; }
        public virtual DbSet<LuuCV> LuuCV { get; set; }
        public virtual DbSet<LuuTin> LuuTin { get; set; }
        public virtual DbSet<NHATUYENDUNG> NHATUYENDUNG { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<UNGVIEN> UNGVIEN { get; set; }
        public virtual DbSet<TinXinViec> TinXinViec { get; set; }
        public virtual DbSet<TinNhan> TinNhan { get; set; }
        public virtual DbSet<TinNhan_ChiTietTin> TinNhan_ChiTietTin { get; set; }
    }
}
