//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhDang_rtbx_UV
    {
        public string Id { get; set; }
        public string RtbxStyle { get; set; }
        public string Color { get; set; }
        public string Font { get; set; }
        public string FontStyle { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual CVs CVs { get; set; }
    }
}
