//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPostings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPostings()
        {
            this.Applications = new HashSet<Applications>();
            this.DinhDang_rtbx_NTD = new HashSet<DinhDang_rtbx_NTD>();
            this.LuuTin = new HashSet<LuuTin>();
            this.LuuCV = new HashSet<LuuCV>();
        }
    
        public string IdCompany { get; set; }
        public string IdJobPostings { get; set; }
        public string IconCompany { get; set; }
        public string Job { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Experience { get; set; }
        public string WorkFormat { get; set; }
        public string DatePosted { get; set; }
        public string Deadline { get; set; }
        public string JobDescription { get; set; }
        public string Requirements { get; set; }
        public string Benefit { get; set; }
        public string Activity { get; set; }
        public string Award { get; set; }
        public string License { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DinhDang_rtbx_NTD> DinhDang_rtbx_NTD { get; set; }
        public virtual NHATUYENDUNG NHATUYENDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuuTin> LuuTin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuuCV> LuuCV { get; set; }
    }
}
