//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public string IdCompany { get; set; }
        public string IdJobPostings { get; set; }
        public string IdCandidate { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string DateSent { get; set; }
        public string InterviewDate { get; set; }
        public string InterViewTime { get; set; }
    }
}
