//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichPhongVan
    {
        public string IdCompany { get; set; }
        public string IdJobPostings { get; set; }
        public string IdCandidate { get; set; }
        public string LinkAvatar { get; set; }
        public string UpdateDate { get; set; }
        public string InterviewDate { get; set; }
        public string InterviewTime { get; set; }
        public string JobName { get; set; }
        public string CandidateName { get; set; }
    }
}
