//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHATUYENDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHATUYENDUNG()
        {
            this.JobPostings = new HashSet<JobPostings>();
        }
    
        public string Id { get; set; }
        public string UserType { get; set; }
        public string Fname { get; set; }
        public string Email { get; set; }
        public string PhoneNTD { get; set; }
        public string JobPos { get; set; }
        public string Company { get; set; }
        public string JobLocation { get; set; }
        public string SocialNetwork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostings> JobPostings { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
