//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string Id { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    
        public virtual NHATUYENDUNG NHATUYENDUNG { get; set; }
        public virtual UNGVIEN UNGVIEN { get; set; }
    }
}
