//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan_ChiTietTin
    {
        public string IdJobPostings { get; set; }
        public string Id { get; set; }
        public string DateSent { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    }
}
