//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Windows_04.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Windows_04.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0669a73f_6c59_47e6_b77d_8d4b6eb6f99f {
            get {
                object obj = ResourceManager.GetObject("_0669a73f-6c59-47e6-b77d-8d4b6eb6f99f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0669a73f_6c59_47e6_b77d_8d4b6eb6f99f1 {
            get {
                object obj = ResourceManager.GetObject("_0669a73f-6c59-47e6-b77d-8d4b6eb6f99f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2fa2f5bdd1a10 {
            get {
                object obj = ResourceManager.GetObject("2fa2f5bdd1a10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _512x512 {
            get {
                object obj = ResourceManager.GetObject("512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _CITYPNG_COM_Flat_Green_Like_Heart_Icon_Silhouette_Transparent_Background___4000x4000 {
            get {
                object obj = ResourceManager.GetObject("[CITYPNG.COM]Flat Green Like Heart Icon Silhouette Transparent Background - 4000x" +
                        "4000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap briefcase {
            get {
                object obj = ResourceManager.GetObject("briefcase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_checkmark_icon {
            get {
                object obj = ResourceManager.GetObject("calendar-checkmark-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_with_check_mark_75624 {
            get {
                object obj = ResourceManager.GetObject("calendar-with-check-mark_75624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar1 {
            get {
                object obj = ResourceManager.GetObject("Calendar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap date_and_time_icon {
            get {
                object obj = ResourceManager.GetObject("date-and-time-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap experience {
            get {
                object obj = ResourceManager.GetObject("experience", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favpng_dollar_sign_currency_symbol_united_states_dollar_icon {
            get {
                object obj = ResourceManager.GetObject("favpng_dollar-sign-currency-symbol-united-states-dollar-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favpng_dollar_sign_currency_symbol_united_states_dollar_icon1 {
            get {
                object obj = ResourceManager.GetObject("favpng_dollar-sign-currency-symbol-united-states-dollar-icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap follow_42_32 {
            get {
                object obj = ResourceManager.GetObject("follow-42-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart_icon_3339 {
            get {
                object obj = ResourceManager.GetObject("heart-icon-3339", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart_icon_33391 {
            get {
                object obj = ResourceManager.GetObject("heart-icon-33391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart_icon_3351 {
            get {
                object obj = ResourceManager.GetObject("heart-icon-3351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Iconsmind_Outline_Close_Window_512 {
            get {
                object obj = ResourceManager.GetObject("Iconsmind-Outline-Close-Window.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isometric_landing_page_design_background_template {
            get {
                object obj = ResourceManager.GetObject("isometric-landing-page-design-background-template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap job_942800 {
            get {
                object obj = ResourceManager.GetObject("job_942800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap job_post {
            get {
                object obj = ResourceManager.GetObject("job-post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap job_post1 {
            get {
                object obj = ResourceManager.GetObject("job-post1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_birthday_cake_bakery_wedding_cake_computer_icons_birth_date_5b2ec694aff869_8062975015297921487208 {
            get {
                object obj = ResourceManager.GetObject("kisspng-birthday-cake-bakery-wedding-cake-computer-icons-birth-date-5b2ec694aff86" +
                        "9.8062975015297921487208", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_chief_executive_computer_icons_businessperson_5aeaec59c56a80_3532939915253453698086 {
            get {
                object obj = ResourceManager.GetObject("kisspng-chief-executive-computer-icons-businessperson-5aeaec59c56a80.353293991525" +
                        "3453698086", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_clip_art_computer_icons_portable_network_graphics_font_work_svg_png_icon_free_download_391838_o_5c65783be93e67_4416976315501537879554 {
            get {
                object obj = ResourceManager.GetObject("kisspng-clip-art-computer-icons-portable-network-graphics-font-work-svg-png-icon-" +
                        "free-download-391838-o-5c65783be93e67.4416976315501537879554", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_clip_art_computer_icons_scalable_vector_graphics_p_earth_location_map_world_navigation_pin_marker_svg_5bf236c7224d20_4334433015426003911405 {
            get {
                object obj = ResourceManager.GetObject("kisspng-clip-art-computer-icons-scalable-vector-graphics-p-earth-location-map-wor" +
                        "ld-navigation-pin-marker-svg-5bf236c7224d20.4334433015426003911405", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_chat_room_online_chat_web_chat_message_box_5acea927f288e3_5629845315234931599934 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-chat-room-online-chat-web-chat-message-box-5acea927f288e3." +
                        "5629845315234931599934", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_door_symbol_building_5b383c2f2dc4f1_6946621115304120791875 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-door-symbol-building-5b383c2f2dc4f1.6946621115304120791875" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_door_symbol_building_5b383c2f2dc4f11 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-door-symbol-building-5b383c2f2dc4f11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_download_clip_art_name_tag_5ac0f763d08452_7040853015225956838541 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-download-clip-art-name-tag-5ac0f763d08452.7040853015225956" +
                        "838541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_editing_vector_graphics_editor_edit_pen_write_icon_5ab06a247f5929_0215497815215109485216 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-editing-vector-graphics-editor-edit-pen-write-icon-5ab06a2" +
                        "47f5929.0215497815215109485216", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_experience_stagiair_experience_5b20efb2862eb5_9663932815288851705496 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-experience-stagiair-experience-5b20efb2862eb5.966393281528" +
                        "8851705496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_five_pointed_star_circle_circulo_5ac930dde65260_0800085015231346859434 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-five-pointed-star-circle-circulo-5ac930dde65260.0800085015" +
                        "231346859434", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_floppy_disk_clip_art_save_button_5ac537556da855_9206579915228741974492 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-floppy-disk-clip-art-save-button-5ac537556da855.9206579915" +
                        "228741974492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_gear_setting_5b132e719ea563_8000613215279837296498__1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-gear-setting-5b132e719ea563.8000613215279837296498 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_hierarchy_5ae173f77b01a9_2322034515247247275038 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-hierarchy-5ae173f77b01a9.2322034515247247275038", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_information_clip_art_5aff14d9042d81_0094381815266664570171 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-information-clip-art-5aff14d9042d81.0094381815266664570171" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_investor_investment_bank_symbols_salary_5ab0ffad142d79_5467246115215492290827 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-investor-investment-bank-symbols-salary-5ab0ffad142d79.546" +
                        "7246115215492290827", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_license_symbol_contract_5b34684f58b2f9_7362197615301612313634 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-license-symbol-contract-5b34684f58b2f9.7362197615301612313" +
                        "634", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_public_key_certificate_font_awesome_5b2e4473618a98_7364413415297588353995 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-public-key-certificate-font-awesome-5b2e4473618a98.7364413" +
                        "415297588353995", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_speed_test_timer_5acae4113a3aa0_6184639815232460972385 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-speed-test-timer-5acae4113a3aa0.6184639815232460972385", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_stock_photography_email_clip_art_simblo_5b4faed30f1343_1676878115319487550618 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-stock-photography-email-clip-art-simblo-5b4faed30f1343.167" +
                        "6878115319487550618", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_symbol_history_material_5ac8c678eea467_1147393315231074489775 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-symbol-history-material-5ac8c678eea467.1147393315231074489" +
                        "775", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_work_experience_clip_art_experiential_5b06897787b6b0_7873029515271550635559 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-work-experience-clip-art-experiential-5b06897787b6b0.78730" +
                        "29515271550635559", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_corporation_corporate_services_logo_brand_corporate_identity_icon_5b4b4286bd9ff6_7704482815316588867767 {
            get {
                object obj = ResourceManager.GetObject("kisspng-corporation-corporate-services-logo-brand-corporate-identity-icon-5b4b428" +
                        "6bd9ff6.7704482815316588867767", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_gender_symbol_female_5ada9ac3046e66_5026924515242759070182 {
            get {
                object obj = ResourceManager.GetObject("kisspng-gender-symbol-female-5ada9ac3046e66.5026924515242759070182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_hierarchical_organization_business_management_hier_5b2fc32ab90b81_829071621529856810758 {
            get {
                object obj = ResourceManager.GetObject("kisspng-hierarchical-organization-business-management-hier-5b2fc32ab90b81.8290716" +
                        "21529856810758", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_registered_trademark_symbol_service_mark_logo_dollar_sign_5ac0152346edc2_4227167215225377632905 {
            get {
                object obj = ResourceManager.GetObject("kisspng-registered-trademark-symbol-service-mark-logo-dollar-sign-5ac0152346edc2." +
                        "4227167215225377632905", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_rubbish_bins_waste_paper_baskets_computer_icons_lixo_5b25c01b15f310_9266541715292006670899 {
            get {
                object obj = ResourceManager.GetObject("kisspng-rubbish-bins-waste-paper-baskets-computer-icons-lixo-5b25c01b15f310.92665" +
                        "41715292006670899", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_scalable_vector_graphics_computer_icons_portable_n_snowbears_5cb7a84816f6b3_8180413815555400400941 {
            get {
                object obj = ResourceManager.GetObject("kisspng-scalable-vector-graphics-computer-icons-portable-n-snowbears-5cb7a84816f6" +
                        "b3.8180413815555400400941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_star_silhouette_shape_clip_art_rating_star_5b51bfe0b58f29_8480018315320841927437 {
            get {
                object obj = ResourceManager.GetObject("kisspng-star-silhouette-shape-clip-art-rating-star-5b51bfe0b58f29.848001831532084" +
                        "1927437", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_stopwatch_clock_clip_art_stopwatch_cliparts_5a7600c24b7758_0680084115176828823091 {
            get {
                object obj = ResourceManager.GetObject("kisspng-stopwatch-clock-clip-art-stopwatch-cliparts-5a7600c24b7758.06800841151768" +
                        "28823091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_stopwatch_timer_clip_art_stopwatch_cliparts_5a76b357e59d45_0215386115177285999405 {
            get {
                object obj = ResourceManager.GetObject("kisspng-stopwatch-timer-clip-art-stopwatch-cliparts-5a76b357e59d45.02153861151772" +
                        "85999405", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_template_green_frame_5a7fd510f0a857_8461228615183270569857 {
            get {
                object obj = ResourceManager.GetObject("kisspng-template-green-frame-5a7fd510f0a857.8461228615183270569857", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap klipartz_com {
            get {
                object obj = ResourceManager.GetObject("klipartz.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap klipartz_com__1_ {
            get {
                object obj = ResourceManager.GetObject("klipartz.com (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap klipartz_com__2_ {
            get {
                object obj = ResourceManager.GetObject("klipartz.com (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap klipartz_com__3_ {
            get {
                object obj = ResourceManager.GetObject("klipartz.com (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovepik_com_400306429_photo_album {
            get {
                object obj = ResourceManager.GetObject("Lovepik_com-400306429-photo-album", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovepik_com_401710061_money {
            get {
                object obj = ResourceManager.GetObject("Lovepik_com-401710061-money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovepik_com_401714979_characters_of_different_professions {
            get {
                object obj = ResourceManager.GetObject("Lovepik_com-401714979-characters-of-different-professions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovepik_com_450161447_Cute_frame_border_png_picture_image {
            get {
                object obj = ResourceManager.GetObject("Lovepik_com-450161447-Cute frame border png picture image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_icon {
            get {
                object obj = ResourceManager.GetObject("name-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_hamburger_menu_png_1276180 {
            get {
                object obj = ResourceManager.GetObject("NicePng_hamburger-menu-png_1276180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noun_experience_2036014 {
            get {
                object obj = ResourceManager.GetObject("noun-experience-2036014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg {
            get {
                object obj = ResourceManager.GetObject("pngegg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__14_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (14)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__15_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (15)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__16_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (16)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__17_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (17)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__18_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (18)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__19_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (19)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__20_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (20)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__21_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (21)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__22_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (22)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__23_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (23)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngfind_com_ticket_icon_png_3159127 {
            get {
                object obj = ResourceManager.GetObject("pngfind.com-ticket-icon-png-3159127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__1_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__2_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__3_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing1 {
            get {
                object obj = ResourceManager.GetObject("pngwing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing2 {
            get {
                object obj = ResourceManager.GetObject("pngwing2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing3 {
            get {
                object obj = ResourceManager.GetObject("pngwing3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing4 {
            get {
                object obj = ResourceManager.GetObject("pngwing4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resume_Bullet_Point_Examples_e1655961799309 {
            get {
                object obj = ResourceManager.GetObject("Resume-Bullet-Point-Examples-e1655961799309", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Roundicons_100_Free_Solid_Cancel_512 {
            get {
                object obj = ResourceManager.GetObject("Roundicons-100-Free-Solid-Cancel.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salary {
            get {
                object obj = ResourceManager.GetObject("salary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_02_29_004258 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-02-29 004258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_03_05_2045131 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-05 2045131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_03_05_2045132 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-05 2045132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_19_093538 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-19 093538", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send_2089310 {
            get {
                object obj = ResourceManager.GetObject("send_2089310", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_company_icon_office_building_icon_human_resources_5f8e10bd66c854_033630951603145917421 {
            get {
                object obj = ResourceManager.GetObject("transparent-company-icon-office-building-icon-human-resources-5f8e10bd66c854.0336" +
                        "30951603145917421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_login_avatar_11925 {
            get {
                object obj = ResourceManager.GetObject("user-login-avatar-11925", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_o_email_e_enviar_icone_preto_20009601 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_o-email-e-enviar-icone-preto_20009601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_o_email_e_enviar_icone_preto_200096011 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_o-email-e-enviar-icone-preto_200096011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
